// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3jlLc7xzGOoyH3w3uXE_Jg8iA1TEwps',
    appId: '1:729913344857:web:b1e3efd94701b570260248',
    messagingSenderId: '729913344857',
    projectId: 'hitesh-app-9d32a',
    authDomain: 'hitesh-app-9d32a.firebaseapp.com',
    storageBucket: 'hitesh-app-9d32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTSlwgZY2nfODM1Zj5N89KUj1U88lCYio',
    appId: '1:729913344857:android:20959d0bf18d0170260248',
    messagingSenderId: '729913344857',
    projectId: 'hitesh-app-9d32a',
    storageBucket: 'hitesh-app-9d32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodXs8mnYCqzJCr4JN3meEn_9Glmaun9A',
    appId: '1:729913344857:ios:de9fb232b1747232260248',
    messagingSenderId: '729913344857',
    projectId: 'hitesh-app-9d32a',
    storageBucket: 'hitesh-app-9d32a.appspot.com',
    iosBundleId: 'com.example.schoolAnnouncements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodXs8mnYCqzJCr4JN3meEn_9Glmaun9A',
    appId: '1:729913344857:ios:de9fb232b1747232260248',
    messagingSenderId: '729913344857',
    projectId: 'hitesh-app-9d32a',
    storageBucket: 'hitesh-app-9d32a.appspot.com',
    iosBundleId: 'com.example.schoolAnnouncements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3jlLc7xzGOoyH3w3uXE_Jg8iA1TEwps',
    appId: '1:729913344857:web:521da3887b3a3e25260248',
    messagingSenderId: '729913344857',
    projectId: 'hitesh-app-9d32a',
    authDomain: 'hitesh-app-9d32a.firebaseapp.com',
    storageBucket: 'hitesh-app-9d32a.appspot.com',
  );
}
